<?php

$cattleHerdGroups = [
    'Calves Group',
    'Heifer',
    'Cows (lactating)',
    'Pregnant Cows',
    'Dry Cows',
    'Bulls',
    'Steer (castrated male)',
    'Other',
];

$cattleFarmingMethods = [
    'Intensive',
    'Semi-Intensive',
    'Extensive',
    'Free Range',
    'Zero Grazing',
    'Pasture-Based',
    'Organic',
    'Commercial',
    'Backyard',
    'Mixed System',
    'Nomadic / Pastoral',
    'Feedlot',
    'Other',
];

$cattleFeedingMethods = [
    'Stall Feeding',
    'Grazing',
    'Rotational Grazing',
    'Zero Grazing (Cut-and-Carry)',
    'Semi-Intensive Feeding',
    'Intensive Feeding',
    'Free Feeding (Ad libitum)',
    'Restricted Feeding (Controlled rationing)',
    'Hand Feeding',
    'Mechanical Feeding',
    'TMR (Total Mixed Ration)',
    'Pasture Grazing',
    'Supplementary Feeding',
    'Mixed Feeding System',
    'Automatic Feeding System',
    'Bucket Feeding (common in dairy calves)',
    'Creep Feeding (young animals)',
    'Other',
];

return [

    'default' => 'cattle',

    'keys' => ['cattle', 'poultry'],

    'labels' => [
        'cattle' => 'Cattle / dairy',
        'poultry' => 'Poultry',
    ],

    'profiles' => [
        'cattle' => [
            'label' => 'Cattle / dairy',
            'stock_unit' => 'individual',
            'modules' => [
                'dashboard',
                'farms',
                'livestock',
                'animals',
                'employees',
                'health',
                'feeding',
                'feed-calculator',
                'milk',
                'breeding',
                'certificates',
                'movement',
                'sales',
                'customers',
                'expenses',
                'finance',
            ],
            'sale_types' => ['animal_sale', 'meat_sale', 'milk_sale'],
            'hidden_sale_sections' => [],
            'herd_groups' => $cattleHerdGroups,
            'livestock_types' => [
                'Cattle',
                'Goat',
                'Sheep',
                'Pig',
                'Poultry',
                'Rabbit',
                'Fish',
                'Camel',
                'Donkey',
                'Horse',
                'Bee Colony',
                'Mixed Livestock',
                'Other',
            ],
            'production_purposes' => [
                'Meat Production',
                'Dairy Production',
                'Breeding',
                'Other',
            ],
            'farming_methods' => $cattleFarmingMethods,
            'feeding_methods' => $cattleFeedingMethods,
            'production_statuses' => [
                'Lactating',
                'Dry',
                'Growing',
                'Breeding',
                'Fattening',
                'Gestating',
                'Not applicable',
            ],
            'labels' => [
                'stock' => 'Animal',
                'stock_plural' => 'Animals',
                'group' => 'Herd group',
                'group_section' => 'Group / herd',
                'group_help' => 'Cattle group or herd classification — select all that apply.',
            ],
        ],
        'poultry' => [
            'label' => 'Poultry',
            'stock_unit' => 'flock',
            'modules' => [
                'dashboard',
                'farms',
                'livestock',
                'flocks',
                'employees',
                'health',
                'feeding',
                'feed-calculator',
                'eggs',
                'certificates',
                'movement',
                'sales',
                'customers',
                'expenses',
                'finance',
            ],
            'sale_types' => ['animal_sale', 'egg_sale', 'meat_sale'],
            'hidden_sale_sections' => ['abattoir'],
            'herd_groups' => [
                'Day-old chicks',
                'Pullets',
                'Layers',
                'Broilers',
                'Breeders',
                'Cockerels',
                'Other',
            ],
            'livestock_types' => [
                'Poultry',
                'Other',
            ],
            'production_purposes' => [
                'Egg Production',
                'Meat Production',
                'Breeding',
                'Other',
            ],
            'farming_methods' => [
                'Intensive',
                'Semi-Intensive',
                'Free Range',
                'Backyard',
                'Commercial',
                'Cage System',
                'Deep Litter',
                'Free Run',
                'Organic',
                'Other',
            ],
            'feeding_methods' => [
                'Intensive Feeding',
                'Free Feeding (Ad libitum)',
                'Restricted Feeding (Controlled rationing)',
                'Hand Feeding',
                'Mechanical Feeding',
                'Automatic Feeding System',
                'Mixed Feeding System',
                'Other',
            ],
            'production_statuses' => [
                'Laying',
                'Growing',
                'Broiler',
                'Breeding',
                'Not applicable',
            ],
            'labels' => [
                'stock' => 'Flock',
                'stock_plural' => 'Flocks',
                'group' => 'House / flock group',
                'group_section' => 'House / flock group',
                'group_help' => 'Classify this poultry house or flock group — select all that apply.',
            ],
        ],
    ],

    'route_modules' => [
        'animals' => 'animals',
        'milk' => 'milk',
        'breeding' => 'breeding',
        'flocks' => 'flocks',
        'eggs' => 'eggs',
        'sales.abattoir' => 'abattoir',
    ],

];
